version: '2'

services:
    php-apache:
            build: apache
            container_name: php-apache
            ports :
               - "80:80"
            volumes:
                - ${WORKSPACE_APP_PATH}:/var/www/workspace
            links:
                - db

    db:
        user: "1000:50"
        image: mysql
        container_name: db
        command: mysqld --sql_mode=""
        ports:
            - "3306:3306"
        volumes:
            - ${MYSQL_PATH}:/var/lib/mysql
            - ${WORKSPACE_APP_PATH}:/var/www/workspace
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
            image: phpmyadmin/phpmyadmin
            container_name: phpmyadmin
            volumes:
            - ${CONFIG_FILE}:/etc/phpmyadmin/config.user.inc.php
            ports:
                - "8080:80"
            links:
                - db

    varnish:
        image: biko2/docker-varnish
        container_name: varnish
        ports:
            - "8000:80"
        tty: true
        environment:
            VARNISH_BACKEND_PORT: 80
            VARNISH_BACKEND_IP: ${VARNISH_BACKEND_IP}
            VARNISH_PORT: 80
            VARNISH_MEMORY: 100M

